//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;
using System.Xml.Serialization;

namespace RealTimeChattingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendsTable
    {
        public int ID { get; set; }
        public Nullable<int> Friend1ID { get; set; }
        public Nullable<int> Friend2ID { get; set; }
        public string Time { get; set; }
       /* [JsonIgnore, XmlIgnore]*/
        public virtual UserInfo UserInfo { get; set; }
      /*  [JsonIgnore, XmlIgnore]*/

        public virtual UserInfo UserInfo1 { get; set; }
    }
}
