//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeChattingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequest
    {
        public int ID { get; set; }
        public Nullable<int> RequstSender { get; set; }
        public Nullable<int> RequstReciver { get; set; }
        public string Time { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
    }
}
