//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;
using System.Xml.Serialization;



namespace RealTimeChattingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMsg
    {
        public int ID { get; set; }
        public string Msg { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> SenderID { get; set; }
        [JsonIgnore, XmlIgnore]
        public virtual GroupInfo GroupInfo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
