//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeChattingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string JoinTime { get; set; }
        public string Rank { get; set; }
        public string GroupName { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
