//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeChattingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginActivity
    {
        public int ID { get; set; }
        public string IP { get; set; }
        public string Address { get; set; }
        public string Time { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Region { get; set; }
    }
}
