//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeChattingBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Realtime_ChattingEntities : DbContext
    {
        public Realtime_ChattingEntities()
            : base("name=Realtime_ChattingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TokenTable> TokenTables { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<FriendsTable> FriendsTables { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<FriendRequest> FriendRequests { get; set; }
    }
}
