
export const AUTH_START= 'AUTH_START'; 
export const AUTH_SUCCESS= 'AUTH_SUCCESS'; 
export const AUTH_FAILED= 'AUTH_FAILED'; 
export const AUTH_LOGOUT= 'AUTH_LOGOUT'; 
export const AUTH_LOGOUT_FROMOTHER_DEVICE= 'AUTH_LOGOUT_FROMOTHER_DEVICE'; 

export const LOGINACTIVITYLIST= 'LOGINACTIVITYLIST';

export const MESSAGE= 'MESSAGE';
export const FRIEDNS= 'FRIEDNS';
export const FRIEDNVERIFY= 'FRIEDNVERIFY';
export const FRIENDREQMSG= 'FRIENDREQMSG';
export const FRIENDREQLIST= 'FRIENDREQLIST';
export const FRIENDREQACTION= 'FRIENDREQACTION';
export const UNFRIENDSUCESS= 'UNFRIENDSUCESS';


export const GROUP_DATA= 'GROUP_DATA';
export const GROUP_MEMBER_VALIDATION= 'GROUP_MEMBER_VALIDATION';
export const GROUP_LIST= 'GROUP_LIST';